/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgraph-latest-bsd-src/examples/org/jgraph/example/GroupingRemoving.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./junit-4.11-sources/org/junit/internal/runners/statements/ExpectException.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/javax/servlet/http/HttpServlet.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./aspectj-1.6.9-src/aspectjtools1.6.9-src/org/aspectj/weaver/loadtime/Agent.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./aspectj-1.6.9-src/aspectjweaver1.6.9-src/org/aspectj/weaver/loadtime/Agent.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/core/org/apache/hadoop/io/WritableComparator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/core/org/apache/hadoop/util/StringUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/examples/org/apache/hadoop/examples/DBCountPageView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/examples/org/apache/hadoop/examples/DBCountPageView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/mapred/org/apache/hadoop/mapred/LineRecordReader.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/mapred/org/apache/hadoop/mapreduce/JobSubmissionFiles.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/mapred/org/apache/hadoop/mapreduce/lib/input/LineRecordReader.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/mapred/org/apache/hadoop/mapreduce/lib/output/TextOutputFormat.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/test/org/apache/hadoop/mapred/TestJobCounters.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/criterion/Example.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/dialect/pagination/SQLServer2005LimitHandler.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/service/jdbc/connections/internal/ConnectionProviderInitiator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaUpdate.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jasperreports-3.7.4/src/net/sf/jasperreports/engine/design/JRVerifier.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/plot/SpiderWebPlot.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/plot/SpiderWebPlot.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/renderer/xy/AbstractXYItemRenderer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/data/KeyToGroupMap.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgraph-latest-bsd-src/examples/org/jgraph/example/HelloWorld.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgraph-latest-bsd-src/examples/org/jgraph/example/HelloWorld.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgraph-latest-bsd-src/examples/org/jgraph/example/HelloWorld.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgraph-latest-bsd-src/examples/org/jgraph/example/HelloWorld.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./junit-4.11-sources/org/junit/Assert.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./junit-4.11-sources/org/junit/rules/ExternalResource.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/catalina/authenticator/BasicAuthenticator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/catalina/authenticator/BasicAuthenticator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/catalina/authenticator/FormAuthenticator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/catalina/connector/CoyoteAdapter.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/catalina/connector/CoyoteAdapter.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/jasper/runtime/JspRuntimeLibrary.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/alert/GoogleMail.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/alert/GoogleMail.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/ShortestPathDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/ShortestPathDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./poi-3.6-20091214/poi-3.6/src/ooxml/java/org/apache/poi/ss/usermodel/WorkbookFactory.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.data/src/main/java/org/springframework/data/factory/support/AutowireUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.data/src/main/java/org/springframework/data/propertyeditors/CustomCollectionEditor.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.context/src/main/java/org/springframework/scheduling/config/ScheduledTasksBeanDefinitionParser.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.core/src/main/java/org/springframework/util/DefaultPropertiesPersister.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.oxm/src/main/java/org/springframework/oxm/jaxb/Jaxb2Marshaller.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.test/src/main/java/org/springframework/mock/web/DelegatingServletInputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web.servlet/src/main/java/org/springframework/web/servlet/DispatcherServlet.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web.servlet/src/test/java/org/springframework/mock/web/DelegatingServletInputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web/src/test/java/org/springframework/mock/web/DelegatingServletInputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/core/src/main/java/org/apache/struts2/dispatcher/mapper/DefaultActionMapper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/cfg/SettingsFactory.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jasperreports-3.7.4/src/net/sf/jasperreports/engine/design/JRVerifier.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web.servlet/src/main/java/org/springframework/web/servlet/mvc/annotation/AnnotationMethodHandlerExceptionResolver.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web.servlet/src/main/java/org/springframework/web/servlet/mvc/annotation/DefaultAnnotationHandlerMapping.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-ant-1.8.4/src/main/org/apache/tools/ant/taskdefs/Mkdir.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/core/org/apache/hadoop/io/serializer/DeserializerComparator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/examples/org/apache/hadoop/examples/WordCount.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/examples/org/apache/hadoop/examples/WordCount.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/examples/org/apache/hadoop/examples/WordCount.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/mapred/org/apache/hadoop/mapreduce/lib/map/TokenCounterMapper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/flush_and_clear_session.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/using_a_StatelessSession.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/cfg/Environment.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-entitymanager/src/main/java/org/hibernate/ejb/criteria/QueryStructure.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-envers/src/test/java/org/hibernate/envers/test/integration/basic/RegisterUserEventListenersTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgrapht-0.8.1/src/org/jgrapht/experimental/touchgraph/TouchgraphConverter.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/contribs/JimMoore/LoggingOutputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/src/main/java/org/apache/log4j/DailyRollingFileAppender.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/src/main/java/org/apache/log4j/net/SMTPAppender.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/src/main/java/org/apache/log4j/WriterAppender.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./poi-3.6-20091214/poi-3.6/src/examples/src/org/apache/poi/ss/examples/CalendarDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./poi-3.6-20091214/poi-3.6/src/examples/src/org/apache/poi/ss/examples/CalendarDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.aop/src/main/java/org/springframework/aop/interceptor/ExposeBeanNameAdvisors.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web.servlet/src/main/java/org/springframework/web/servlet/DispatcherServlet.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.web.servlet/src/main/java/org/springframework/web/servlet/tags/form/ValueFormatter.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/core/Instances.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/core/NormalizableDistance.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/core/NormalizableDistance.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./freecol-0.10.7-src/src/net/sf/freecol/client/gui/menu/FreeColMenuTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/draw/AbstractConstrainer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/draw/AbstractConstrainer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/POIUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jboss-5.1.0.GA-src/console/src/main/org/jboss/console/plugins/helpers/servlet/ServletHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./findbugs-1.3.9/src/antTask/edu/umd/cs/findbugs/anttask/UnionBugs.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./findbugs-1.3.9/src/antTask/edu/umd/cs/findbugs/anttask/UnionBugs.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./wct-package-v1.5.2/WCTSubmitToRosetta/src/main/java/nz/govt/natlib/ndha/common/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/test/org/apache/catalina/tribes/demos/MapDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/VerticalGridLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/VerticalGridLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/VerticalGridLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./wct-package-v1.5.2/WCTSubmitToRosetta/src/main/java/nz/govt/natlib/ndha/common/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/POIUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/POIUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/draw/AbstractConstrainer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/draw/AbstractConstrainer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./antlr4-4.0/tool/test/org/antlr/v4/test/TestPerformance.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/image/MovieEncoder.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./c-jdbc-2.0.2-src/src/org/objectweb/cjdbc/common/util/FileManagement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/base/src/org/compiere/process/RegisterSystem.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./db-derby-10.6.1.0-src/db-derby-10.6.1.0-src/java/testing/org/apache/derbyTesting/functionTests/tests/junitTests/compatibility/CompatibilityCombinations.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./FitLibrary20100806/fitnesse/lib/src/fitlibrarySrc/fitlibrary/batch/resultsOut/FolderTestResultRepository.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./geotools-2.7-M3/modules/extension/xsd/xsd-wcs/src/main/java/org/geotools/wcs/bindings/TimeSequenceTypeBinding.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./geotools-2.7-M3/modules/unsupported/swing/src/main/java/org/jdesktop/swingworker/SwingWorker.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./geotools-2.7-M3/modules/unsupported/swing/src/main/java/org/jdesktop/swingworker/SwingWorker.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hadoop-1.0.0/src/core/org/apache/hadoop/io/file/tfile/SimpleBufferedOutputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./heritrix-1.14.4/src/java/org/archive/util/FileUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/using_scroll.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/documentation/src/main/docbook/devguide/en-US/extras/using_scroll.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/action/internal/BulkOperationCleanupAction.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/dialect/Oracle9iDialect.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hibernate-release-4.2.2.Final/project/hibernate-core/src/main/java/org/hibernate/tool/hbm2ddl/SchemaUpdate.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./hsqldb-2.0.0/hsqldb/src/org/hsqldb/test/HsqldbTestCase.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/ireport-designer/src/com/jaspersoft/ireport/designer/sheet/editors/box/ShapeStroke.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperreports-components/src/com/jaspersoft/ireport/components/spiderchart/SpiderChartIcon.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iText-src-5.0.3/core/com/itextpdf/text/pdf/PdfWriter.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jag-6.1/src/com/finalist/jaggenerator/LibCopier.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jboss-5.1.0.GA-src/tomcat/src/main/org/jboss/web/tomcat/security/authenticators/JASPIFormAuthenticator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jboss-5.1.0.GA-src/tomcat/src/main/org/jboss/web/tomcat/security/FormAuthenticator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jboss-5.1.0.GA-src/tomcat/src/main/org/jboss/web/tomcat/security/jaspi/modules/HTTPBasicServerAuthModule.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jboss-5.1.0.GA-src/tomcat/src/main/org/jboss/web/tomcat/security/jaspi/modules/HTTPBasicServerAuthModule.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/demo/BarChartDemo1.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/renderer/xy/AbstractXYItemRenderer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/renderer/xy/AbstractXYItemRenderer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/renderer/xy/AbstractXYItemRenderer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/source/org/jfree/chart/renderer/xy/AbstractXYItemRenderer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/swt/org/jfree/experimental/chart/swt/demo/SWTBarChartDemo1.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/swt/org/jfree/experimental/swt/SWTUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jfreechart-1.0.13/swt/org/jfree/experimental/swt/SWTUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/com/aelitis/azureus/core/util/http/HTTPAuthHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/com/aelitis/azureus/core/util/http/HTTPAuthHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/com/aelitis/azureus/core/util/http/HTTPAuthHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/com/aelitis/azureus/core/util/http/HTTPAuthHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/com/aelitis/azureus/core/util/http/HTTPAuthHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/com/aelitis/azureus/core/util/http/HTTPAuthHelper.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/gudy/azureus2/core3/security/impl/SESecurityManagerImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/plugins/embeddedjsp/src/main/java/org/apache/struts2/jasper/runtime/JspRuntimeLibrary.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/plugins/embeddedjsp/src/main/java/org/apache/struts2/jasper/runtime/JspRuntimeLibrary.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/openide.explorer/src/org/openide/explorer/view/OutlineView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/roller_002dui/errors/_404_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/css_002dnosidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/css_002dsidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/empty_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/empty_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/index_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/roller_002dui/authoring/editors/editor_002dtext_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/roller_002dui/errors/_404_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/roller_002dui/errors/denied_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/roller_002dui/login_002dredirect_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/admin/GlobalConfig_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/admin/PlanetConfig_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/admin/PlanetGroups_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/admin/PlanetSubscriptions_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/core/Login_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/core/MainMenu_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/core/MainMenuSidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/core/UpgradeDatabase_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/EntryAdd_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/EntryEdit_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/EntrySidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/TemplateEdit_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/Templates_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/TemplatesSidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/editor/ThemeEdit_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/bannerInstallation_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/bannerStatus_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/css_002dnosidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/css_002dsidebar_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/empty_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/footer_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/head_002dajax_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/head_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/menu_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/messages_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/tiles_002derrorpage_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/tiles_002dinstallpage_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/tiles_002dmainmenupage_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/tiles_002dsimplepage_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-roller-4.0.1/apache-roller-src-4.0.1/tomcat/work/Catalina/localhost/roller/org/apache/jsp/WEB_002dINF/jsps/tiles/tiles_002dtabbedpage_jsp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/attributeSelection/ReliefFAttributeEval.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/clusterers/FarthestFirst.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/editor.macros/src/org/netbeans/modules/editor/macros/storage/ui/MacrosPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/unit/src/org/netbeans/modules/form/layoutdesign/ALT_Bug124689.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/identity.server.manager/src/org/netbeans/modules/identity/server/manager/ui/ProfileEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/SecurityRolesEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/SecurityRolesEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/src/org/netbeans/modules/java/ui/FmtImports.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/tasklist.todo/src/org/netbeans/modules/tasklist/todo/settings/ToDoCustomizer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/vmd.midpnb/src/org/netbeans/modules/vmd/midpnb/propertyeditors/SVGFormEditorElement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.project/src/org/netbeans/modules/web/project/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.project/src/org/netbeans/modules/web/project/ui/wizards/PanelSupportedFrameworksVisual.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.struts/src/org/netbeans/modules/web/struts/wizards/FormBeanPropertiesPanelVisual.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/websvc.wsitconf/src/org/netbeans/modules/websvc/wsitconf/ui/service/subpanels/TargetsPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/core/Instances.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-jmeter-2.9/apache-jmeter-2.9/src/jorphan/org/apache/jorphan/gui/layout/VerticalLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-jmeter-2.9/apache-jmeter-2.9/src/jorphan/org/apache/jorphan/gui/layout/VerticalLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/src/main/java/org/apache/log4j/lf5/util/StreamUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/kenai.ui/src/org/netbeans/modules/kenai/ui/treelist/TreeList.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/contribs/JimMoore/LoggingOutputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/contribs/JimMoore/LoggingOutputStream.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/util/Images.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/qa-functional/data/SampleDesktopApplication/src/sampledesktopapplication/SampleDesktopView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.examples/MarsRoverViewer/src/marsroverviewer/MarsRoverViewerView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/swingapp/appshells/BasicShellApp/src/applicationpackage/ShellView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/test/unit/data/jdk/JTable.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/tasklist.todo/src/org/netbeans/modules/tasklist/todo/settings/ToDoCustomizer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/tasklist.todo/src/org/netbeans/modules/tasklist/todo/settings/ToDoCustomizer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/kenai/src/org/codeviation/pojson/JsonUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/dlight.perfan/src/org/netbeans/modules/dlight/perfan/util/TasksCachedProcessor.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/unit/src/org/netbeans/modules/form/layoutdesign/ALT_Bug124689.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/identity.server.manager/src/org/netbeans/modules/identity/server/manager/ui/ProfileEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/src/org/netbeans/modules/java/ui/FmtImports.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/vmd.midpnb/src/org/netbeans/modules/vmd/midpnb/propertyeditors/SVGFormEditorElement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/websvc.wsitconf/src/org/netbeans/modules/websvc/wsitconf/ui/service/subpanels/TargetsPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/unit/src/org/netbeans/modules/form/layoutdesign/ALT_Bug124689.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/identity.server.manager/src/org/netbeans/modules/identity/server/manager/ui/ProfileEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/src/org/netbeans/modules/java/ui/FmtImports.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/vmd.midpnb/src/org/netbeans/modules/vmd/midpnb/propertyeditors/SVGFormEditorElement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/xwork-core/src/main/java/com/opensymphony/xwork2/validator/validators/StringLengthFieldValidator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/xwork-core/src/main/java/com/opensymphony/xwork2/validator/validators/StringLengthFieldValidator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-core/src/test/projects/lifecycle-executor/project-with-additional-lifecycle-elements/src/test/java/org/apache/maven/lifecycle/test/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/examples/simple-project/src/test/java/org/apache/maven/embedder/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/test/embedder-test-project/src/test/java/org/apache/maven/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/test/error-reporting-projects/err-resolving-project-dep/project/src/test/java/org/apache/maven/test/error/mojoFailure/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/test/error-reporting-projects/missing-module-pom/child1/src/test/java/org/test/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/test/error-reporting-projects/project-dep-missing/src/test/java/org/apache/maven/test/error/mojoFailure/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/test/error-reporting-projects/project-mojo-failure/src/test/java/org/apache/maven/test/error/mojoFailure/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-maven-3.0/apache-maven-3.0/maven-embedder/src/test/projects/isolated-project-getting-parent-pom/project/src/test/java/org/codehaus/m2eclipse/AppTest.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/ChangeStockInfoJDialog.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./poi-3.6-20091214/poi-3.6/src/examples/src/org/apache/poi/xssf/usermodel/examples/CalendarDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/samples/color/CIEXYChromaticityDiagram.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/dlight.visualizers/src/org/netbeans/modules/dlight/visualizers/CallStackTopComponent.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/dlight.visualizers/src/org/netbeans/modules/dlight/visualizers/ThreadMapTopComponent.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/test/org/apache/catalina/tribes/demos/MapDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.context/src/main/java/org/springframework/context/annotation/ClassPathScanningCandidateComponentProvider.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.context/src/main/java/org/springframework/context/annotation/ClassPathScanningCandidateComponentProvider.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/plaf/palette/PaletteToolBarUI.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/o.mozilla.rhino.patched/patched_files/org/mozilla/nb/javascript/ScriptRuntime.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./spring-framework-3.0.5/spring-framework-3.0.5.RELEASE/projects/org.springframework.context.support/src/main/java/org/springframework/mail/javamail/JavaMailSenderImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/L2RTreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexLabelAsShapeDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-jai-samples-2.0.1/edu/uci/ics/jung/samples/HyperbolicVertexImageShaperDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/AnnotationsDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/DrawnIconVertexDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/GraphEditorDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/GraphFromGraphMLDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/GraphZoomScrollPaneDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/ImageEdgeLabelDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/InternalFrameSatelliteViewDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/L2RTreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/LensDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/LensVertexImageShaperDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/PluggableRendererDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/RadialTreeLensDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/ShowLayouts.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/SubLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/UnicodeLabelDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexCollapseDemoWithLayouts.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexImageShaperDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexLabelAsShapeDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexLabelPositionDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/WorldMapGraphDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-jai-samples-2.0.1/edu/uci/ics/jung/samples/HyperbolicVertexImageShaperDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/AnnotationsDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/BalloonLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/DrawnIconVertexDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/EdgeLabelDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/GraphEditorDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/GraphFromGraphMLDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/GraphZoomScrollPaneDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/ImageEdgeLabelDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/InternalFrameSatelliteViewDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/L2RTreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/LensDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/LensVertexImageShaperDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/PluggableRendererDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/RadialTreeLensDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/ShowLayouts.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/SubLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/UnicodeLabelDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexCollapseDemoWithLayouts.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexImageShaperDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexLabelAsShapeDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexLabelPositionDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/WorldMapGraphDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/L2RTreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeLayoutDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/TreeCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/VertexCollapseDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/qa-functional/src/org/netbeans/qa/form/VisualDevelopmentUtil.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/alert/GoogleMail.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/gui/data/KnowledgeFlowApp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./weka-3-7-9/src/main/java/weka/gui/data/KnowledgeFlowApp.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/unit/src/org/netbeans/modules/form/layoutdesign/ALT_Bug124689.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/identity.server.manager/src/org/netbeans/modules/identity/server/manager/ui/ProfileEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/src/org/netbeans/modules/java/ui/FmtImports.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/vmd.midpnb/src/org/netbeans/modules/vmd/midpnb/propertyeditors/SVGFormEditorElement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/websvc.wsitconf/src/org/netbeans/modules/websvc/wsitconf/ui/service/subpanels/TargetsPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/editor.macros/src/org/netbeans/modules/editor/macros/storage/ui/MacrosPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/unit/src/org/netbeans/modules/form/layoutdesign/ALT_Bug124689.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/identity.server.manager/src/org/netbeans/modules/identity/server/manager/ui/ProfileEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/SecurityRolesEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/SecurityRolesEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/src/org/netbeans/modules/java/ui/FmtImports.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/tasklist.todo/src/org/netbeans/modules/tasklist/todo/settings/ToDoCustomizer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/vmd.midpnb/src/org/netbeans/modules/vmd/midpnb/propertyeditors/SVGFormEditorElement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.project/src/org/netbeans/modules/web/project/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.project/src/org/netbeans/modules/web/project/ui/wizards/PanelSupportedFrameworksVisual.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.struts/src/org/netbeans/modules/web/struts/wizards/FormBeanPropertiesPanelVisual.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/websvc.wsitconf/src/org/netbeans/modules/websvc/wsitconf/ui/service/subpanels/TargetsPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/tomcat/util/http/fileupload/IOUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/test/qa-functional/src/org/netbeans/test/java/Utilities.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/util/Images.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/util/Images.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/editor.macros/src/org/netbeans/modules/editor/macros/storage/ui/MacrosPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/form/test/unit/src/org/netbeans/modules/form/layoutdesign/ALT_Bug124689.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/identity.server.manager/src/org/netbeans/modules/identity/server/manager/ui/ProfileEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.clientproject/src/org/netbeans/modules/j2ee/clientproject/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/SecurityRolesEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ddloaders/src/org/netbeans/modules/j2ee/ddloaders/web/multiview/SecurityRolesEditorPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.ejbjarproject/src/org/netbeans/modules/j2ee/ejbjarproject/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/java.source/src/org/netbeans/modules/java/ui/FmtImports.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/tasklist.todo/src/org/netbeans/modules/tasklist/todo/settings/ToDoCustomizer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/vmd.midpnb/src/org/netbeans/modules/vmd/midpnb/propertyeditors/SVGFormEditorElement.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.project/src/org/netbeans/modules/web/project/ui/customizer/CustomizerLibraries.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.project/src/org/netbeans/modules/web/project/ui/wizards/PanelSupportedFrameworksVisual.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/web.struts/src/org/netbeans/modules/web/struts/wizards/FormBeanPropertiesPanelVisual.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/websvc.wsitconf/src/org/netbeans/modules/websvc/wsitconf/ui/service/subpanels/TargetsPanel.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/VerticalGridLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/VerticalGridLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/debugger.jpda/src/org/netbeans/modules/debugger/jpda/expr/InvocationExceptionTranslated.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/javahelp/src/org/netbeans/modules/javahelp/BrowserDisplayer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/javax/servlet/http/HttpUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/VerticalGridLayout.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/coyote/http11/filters/GzipOutputFilter.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./poi-3.6-20091214/poi-3.6/src/ooxml/java/org/apache/poi/xssf/usermodel/XSSFCell.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/j2ee.sun.ddui/src/org/netbeans/modules/j2ee/sun/validation/util/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jung2-2_0_1/jung-samples-2.0.1/edu/uci/ics/jung/samples/LensDemo.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/util/CachedRowSetImpl.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iReport-3.7.5-src/jasperserver-plugin/src/com/jaspersoft/ireport/jasperserver/ws/IReportTrustManager.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/xwork-core/src/main/java/com/opensymphony/xwork2/validator/validators/StringLengthFieldValidator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/util/Images.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/alert/GoogleMail.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-tomcat-7.0.2/apache-tomcat-7.0.2-src/java/org/apache/tomcat/util/http/fileupload/IOUtils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./struts2-2.2.1-all/struts-2.2.1/src/xwork-core/src/main/java/com/opensymphony/xwork2/util/classloader/JarResourceStore.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jstock-1.0.7c/jstock/src/org/yccheok/jstock/gui/Utils.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jhotdraw-7.5.1/jhotdraw_7.5.1/Source/jhotdraw7/src/main/java/org/jhotdraw/gui/plaf/palette/PaletteListCellRenderer.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./apache-log4j-1.2.16/apache-log4j-1.2.16/src/main/java/org/apache/log4j/net/SMTPAppender.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_EN.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_EN.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./jgraphpad-5.10.0.2-src/src/org/jgraph/pad/graphcellsbase/JGraphSwimlaneView.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_EN.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_FR.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_FR.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_EN.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_FR.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_FR.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_FR.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Compiere_330_Source/ad/src/org/compiere/translate/AmtInWords_FR.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./AoIsrc281/ArtOfIllusion/src/artofillusion/math/SimplexNoise.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./freemind-src-0.9.0/accessories/plugins/dialogs/ArrayListTransferHandler.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./freemind-src-0.9.0/accessories/plugins/dialogs/ArrayListTransferHandler.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./freemind-src-0.9.0/accessories/plugins/dialogs/ArrayListTransferHandler.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./geotools-2.7-M3/modules/unsupported/swing/src/main/java/org/jdesktop/swingworker/SwingWorker.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./iText-src-5.0.3/core/com/itextpdf/text/pdf/BarcodeEAN.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./Vuze_4812_source/org/bouncycastle/crypto/generators/OpenSSLPBEParametersGenerator.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/mobility.midpexamples/LocalizationDemo/src/l10ndemo/LocalizationSupport.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./netbeans-6.9.1-201007282301/properties/src/org/netbeans/modules/properties/UtilConvert.java
/Users/chaiyong/Downloads/ninka-1.3/ninka.pl ./pooka_080505/net/suberic/util/FileVariableBundle.java
